# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'c82e43b2-56df-40bc-b2bb-c6b3cb3993f9'
  imageRepository: 'khhackfestdataapi'
  containerRegistry: 'khcommon.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/data-api/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      name: 'home'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: HelmDeploy@0
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: Cloud-Lab-Workshop-kh-workshop-cluster-hackfest-1580478179331
        namespace: 'hackfest'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: '$(Build.SourcesDirectory)/charts/data-api'
        releaseName: 'data-api'
        overrideValues: 'deploy.acrServer=$(containerRegistry),deploy.imageTag=$(tag)'
        valueFile: '$(Build.SourcesDirectory)/charts/data-api/values.yaml'

